adminapp/urls.py
from django.conf.urls import url

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    url(r'^users/create/$', adminapp.ShopUserCreateView.as_view(), name='user_create'),
    url(r'^users/read/$', adminapp.ShopUserListView.as_view(), name='users'),
    url(r'^users/update/(?P<pk>\d+)/$', adminapp.ShopUserUpdateView.as_view(), name='user_update'),
    url(r'^users/delete/(?P<pk>\d+)/$', adminapp.ShopUserDeleteView.as_view(), name='user_delete'),
    url(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    url(r'^categories/read/$', adminapp.ProductCategoryListView.as_view(), name='categories'),
    url(r'^categories/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    url(r'^categories/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),
    # url(r'^products/create/category/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    # url(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
    # url(r'^products/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    # url(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    # url(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name='login'),
    url(r'^logout/', authapp.logout, name='logout'),
    url(r'^register/', authapp.register, name='register'),
    url(r'edit/', authapp.edit, name='edit'),
    url(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.conf.urls import url

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    url(r'^$', basketapp.basket, name='view'),
    url(r'add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    url('remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url('edit/(?P<pk>\d+)/$', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^contacts/', mainapp.contacts, name='contacts'),
    url(r'^basket/', include('basketapp.urls', namespace='basket')),
    url(r'^admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    url(r'^admin/', admin.site.urls),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   url('^$', mainapp.products, name='index'),
   url(r'^(?P<pk>\d+)/$', mainapp.product, name='product'),
   url(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='имя категория', max_length=128, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory

def get_hot_product():
    return Product.objects.all().first()


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    product_list = Product.objects.all()

    return render(request, 'mainapp/index.html', context={'user': request.user , 'products': product_list})


def products(request, pk=None):
    links_menu = ProductCategory.objects.all()
    # basket = request.user.basket.all()[0] if request.user.is_authenticated else []

    if pk:
        if pk == '0':
            category = {'name': 'Все'}
            product_list = Product.objects.all()
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            product_list = Product.objects.filter(category=category.id)

        context = {
            'title': 'Продукты',
            'links_menu': links_menu,
            'products': product_list,
            'category': category,
        }
        return render(request, 'mainapp/product_list.html', context)
    else:
        product_list = Product.objects.all()

        hot_product = get_hot_product()
        same_products = get_same_products(hot_product)

        context = {
            'title': 'Продукты',
            'links_menu': links_menu,
            'hot_product': hot_product,
            'same_products': same_products,
        }
        return render(request, 'mainapp/products.html', context)


def product(request, pk):
    title = 'Продукт'

    context = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
    }

    return render(request, 'mainapp/product.html', context)


def contacts(request):
    return render(request, 'mainapp/contacts.html')

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:category' 0 %}" 
       class="{% if request.resolver_match.kwargs.pk == '0' %}
                active
              {% endif %}">
      все
    </a>
  </li>
  {% for link in links_menu %}
    <li>
      <a href="{% url 'products:category' link.pk %}" 
         class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                  active
                {% endif %}">
        {{ link.name }}
      </a>
    </li>
  {% endfor %}
</ul>

mainapp/templates/mainapp/includes/inc_menu.html
{% load custom_tags %}

<div class="menu">
    <a class="{% if request.resolver_match.url_name == 'main' %}
    menu-item active
    {% else %}
    menu-item
    {% endif %}" href="{% url 'main' %}">домой</a>
    <a class="{% if request.resolver_match.url_name == 'products' %}
    menu-item active
    {% else %}
    menu-item
    {% endif %}" href="{% url 'products:index' %}">продукты</a>
    <a class="{% if request.resolver_match.url_name == 'contacts' %}
    menu-item active
    {% else %}
    menu-item
    {% endif %}" href="{% url 'contacts' %}">контакты</a>
    {% if request.user.is_superuser %}
    <a href="{% url 'admin_custom:categories' %}">админка</a>
    {% endif %}

    <a href="{% url 'basket:view' %}" class="basket">
      <span>
          {{ request.user|basket_total_cost }}
{#        {% if basket %}#}
{#          {{ basket.total_cost|floatformat:0 }} руб#}
{#          ({{ basket.total_quantity }} шт)#}
{#        {% endif %}#}
      </span>
    </a>
{#    {% if user.is_superuser %}#}
{#        <li>#}
{#          <a href="{% url 'admin_custom:users' %}">админка</a>#}
{#        </li>#}
{#    {% endif %}#}
</div>