authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name='login'),
    url(r'^logout/', authapp.logout, name='logout'),
    url(r'^register/', authapp.register, name='register'),
    url(r'edit/', authapp.edit, name='edit'),
    url(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.conf.urls import url

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    url(r'^$', basketapp.basket, name='view'),
    url(r'add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    url('remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url('edit/(?P<pk>\d+)/$', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^contacts/', mainapp.contacts, name='contacts'),
    url(r'^basket/', include('basketapp.urls', namespace='basket')),
    url(r'^admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    url(r'^admin/', admin.site.urls),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product

class Basket(models.Model):
    class Meta:
        verbose_name = 'Корзина'
        verbose_name_plural = 'Корзины'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

    @property
    def product_cost(self):
        "return cost of all products this type"
        return self.product.price * self.quantity

    @property
    def total_quantity(self):
        "return total quantity for user"
        _items = Basket.objects.filter(user=self.user)
        _totalquantity = sum(list(map(lambda x: x.quantity, _items)))
        return _totalquantity

    @property
    def total_cost(self):
        "return total cost for user"
        _items = Basket.objects.filter(user=self.user)
        _totalcost = sum(list(map(lambda x: x.product_cost, _items)))
        return _totalcost

    def __str__(self):
        return self.user.username + ' ' + self.product.name

basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404, HttpResponse
from basketapp.models import Basket
from mainapp.models import Product
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

@login_required
def basket(request):
    basket_items = request.user.basket.all()
    return render(request, 'basketapp/includes/basket.html', context={'basket_items': basket_items} )

@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('products:product', args=[pk]))

    product = get_object_or_404(Product, pk=pk)

    basket = Basket.objects.filter(user=request.user, product=product).first()

    if not basket:
        basket = Basket(user=request.user, product=product)

    basket.quantity += 1
    basket.save()

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_remove(request, pk):
    basket = request.user.basket.filter(pk=pk).first()

    if basket:
        if basket.quantity > 1:
            basket.quantity -= 1
            basket.save()
        else:
            basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_edit(request, pk, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        new_basket_item = Basket.objects.get(pk=int(pk))

        if quantity > 0:
            new_basket_item.quantity = quantity
            new_basket_item.save()
        else:
            new_basket_item.delete()

        basket_items = Basket.objects.filter(user=request.user). \
            order_by('product__category')

        context = {
            'basket_items': basket_items,
        }

        result = render_to_string('basketapp/includes/inc_basket_list.html', \
                                  context)

        return JsonResponse({'result': result})

basketapp/templates/basketapp/includes/basket.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}


{% block content %}
    <div class="basket_list">
        {% include 'basketapp/includes/inc_basket_list.html' %}
    </div>
    <button class="btn btn-round">
        <a href="{% url 'main' %}">
            на главную
        </a>
    </button>
{% endblock %}

basketapp/templates/basketapp/includes/inc_basket_list.html
{% for item in basket_items %}
    <div>
        <img src="/media{{ item.product.image }}"
             alt="{{ item.product.short }}">
        <span class="category_name">{{ item.product.category.name }}</span>
        <span class="product_name">{{ item.product.name }}</span>
        <span class="product_price">{{ item.product.price }}&nbspруб</span>
        <input type="number" name="{{ item.pk }}"
               min="0"
               value="{{ item.quantity }}">
        <span class="product_cost">{{ item.cost }}</span>

        <a href="{% url 'basket:remove' item.pk %}" class="btn btn-round">
            удалить
        </a>

    </div>
{% endfor %}
{% if basket_items %}
    <div class="basket_summary">
        В корзине {{ basket_items.0.total.quantity }} товаров общей стоимостью
        {{ basket.items.0.total_cost }} руб
    </div>
{% endif %}
<a href="{% url 'main' %}" class="btn btn-round"> на главную</a>