adminapp/urls.py
from django.conf.urls import url

import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    url(r'^users/create/$', adminapp.ShopUserCreateView.as_view(), name='user_create'),
    url(r'^users/read/$', adminapp.ShopUserListView.as_view(), name='users'),
    url(r'^users/update/(?P<pk>\d+)/$', adminapp.ShopUserUpdateView.as_view(), name='user_update'),
    url(r'^users/delete/(?P<pk>\d+)/$', adminapp.ShopUserDeleteView.as_view(), name='user_delete'),
    url(r'^categories/create/$', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    url(r'^categories/read/$', adminapp.ProductCategoryListView.as_view(), name='categories'),
    url(r'^categories/update/(?P<pk>\d+)/$', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    url(r'^categories/delete/(?P<pk>\d+)/$', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),
    # url(r'^products/create/category/(?P<pk>\d+)/$', adminapp.product_create, name='product_create'),
    # url(r'^products/read/category/(?P<pk>\d+)/$', adminapp.products, name='products'),
    # url(r'^products/read/(?P<pk>\d+)/$', adminapp.product_read, name='product_read'),
    # url(r'^products/update/(?P<pk>\d+)/$', adminapp.product_update, name='product_update'),
    # url(r'^products/delete/(?P<pk>\d+)/$', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name='login'),
    url(r'^logout/', authapp.logout, name='logout'),
    url(r'^register/', authapp.register, name='register'),
    url(r'edit/', authapp.edit, name='edit'),
    url(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^contacts/', mainapp.contacts, name='contacts'),
    url(r'^basket/', include('basketapp.urls', namespace='basket')),
    url(r'^admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    url(r'^admin/', admin.site.urls),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from mainapp.models import ProductCategory
from authapp.models import ShopUser


class IsSuperUserView(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class ProductCategoryListView(IsSuperUserView, ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryListView, self).get_context_data(**kwargs)
        context['title'] = 'Список категорий'
        return context

    # @method_decorator(user_passes_test(lambda u: u.is_superuser))
    # def dispatch(self, request, *args, **kwargs):
    #     super(ProductCategoryListView, self).dispatch(self, request, *args, **kwargs)

class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    fields = '__all__'
    success_url = reverse_lazy('admin_custom:categories')

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание категории'
        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    fields = '__all__'
    success_url = reverse_lazy('admin_custom:categories')

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Изменение категории'
        return context


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_custom:categories')

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'Удаление категории'
        return context


class ShopUserListView(IsSuperUserView, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    def get_context_data(self, **kwargs):
        context = super(ShopUserListView, self).get_context_data(**kwargs)
        context['title'] = 'Список пользователей'
        return context

    # @method_decorator(user_passes_test(lambda u: u.is_superuser))
    # def dispatch(self, request, *args, **kwargs):
    #     super(ProductCategoryListView, self).dispatch(self, request, *args, **kwargs)


class ShopUserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    fields = '__all__'
    success_url = reverse_lazy('admin_custom:users')

    def get_context_data(self, **kwargs):
        context = super(ShopUserCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание пользователя'
        return context


class ShopUserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    fields = '__all__'
    success_url = reverse_lazy('admin_custom:users')

    def get_context_data(self, **kwargs):
        context = super(ShopUserUpdateView, self).get_context_data(**kwargs)
        context['title'] = 'Изменение пользователя'
        return context


class ShopUserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_custom:users')

    def get_context_data(self, **kwargs):
        context = super(ShopUserDeleteView, self).get_context_data(**kwargs)
        context['title'] = 'пользователя'
        return context

    def delete(self, request, *args, **kwargs):
        user = get_object_or_404(ShopUser, pk=kwargs['pk'])
        user.is_active = False
        user.save()
        return HttpResponseRedirect(self.success_url)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
</head>
<body>
  <div class="admin_container">
    <div class="h2 text-center head">
      Админка
    </div>
    {% block menu %}
      <div class="admin_menu">
        {% include 'adminapp/includes/inc_menu.html' %}
      </div>
    {% endblock %}

    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
  <div class="categories_list">
    <button class="new_category">
      <a href={% url 'admin_custom:category_create' %}>
        Создать новую категорию
      </a>
    </button>
    <br><br>
    {% for object in object_list %}
      <div class="category_record">
        <b class="category_name">
          {{ object.name|title }}
        </b>
        <div class="category_desc">
          {{ object.description|title }}
        </div>
        <div class="category_actions">
{#          <button>#}
{#            <a href={% url 'admin_custom:products' object.pk %}>#}
{#              товары категории#}
{#            </a>#}
{#          </button>#}
          <button>
            <a href={% url 'admin_custom:category_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin_custom:category_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
      <br>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="удалить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'authapp/base.html' %}
{% load static %}

{% block title %}
    <title>{{ title }}</title>
{% endblock %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:categories' %}">
      к списку категорий
    </a>
  </button>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <div class="products_list">
    <button class="new_product">
      <a href={% url 'admin:product_create' category.pk %}>
        новый продукт
      </a>
    </button>

    {% for object in objects %}
      <div class="product_record">
        <img
          src="/media/{{object.image|default:'products_images/default.jpg'}}"
          alt="{{ object.name }}">
        <div class="product_name">
          {{ object.name|title }}
        </div>
        <div class="product_actions">
          <button>
            <a href={% url 'admin:product_read' object.pk %}>
              подробнее
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_update' object.pk %}>
              редактировать
            </a>
          </button>
          <button>
            <a href={% url 'admin:product_delete' object.pk %}>
              удалить
            </a>
          </button>
        </div>
        <div class="summary">
          <b>цена</b>
          <p>{{ object.price }} руб</p>
          <b>количество</b>
          <p>{{ object.quantity }}</p>
        </div>
        <div class="product_desc">
          {{ object.short_desc|title }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}

adminapp/templates/adminapp/user_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

adminapp/templates/adminapp/user_update.html
    
{% extends 'authapp/base.html' %}
{% load static %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin_custom:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}
© 2019 GitHub, Inc.

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href={% url 'admin_custom:user_create' %}>
                новый пользователь
            </a>
        </button>
        {% for object in object_list %}
            <div
                    class="user_record {% if not object.is_active %}not_active{% endif %}">
                <img
                        src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
                        alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        <a href={% url 'admin_custom:user_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'admin_custom:user_delete' object.pk %}>
                            удалить
                        </a>
                    </button>
                </div>
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                            {% if object.last_name %}
                                <p>{{ object.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}