authapp/urls.py
from django.conf.urls import url

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    url(r'^login/', authapp.login, name='login'),
    url(r'^logout/', authapp.logout, name='logout'),
    url(r'^register/', authapp.register, name='register'),
    url(r'edit/', authapp.edit, name='edit'),
    url(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.conf.urls import url

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    url(r'^$', basketapp.basket, name='view'),
    url(r'add/(?P<pk>\d+)/$', basketapp.basket_add, name='add'),
    url('remove/(?P<pk>\d+)/$', basketapp.basket_remove, name='remove'),
    url('edit/(?P<pk>\d+)/$', basketapp.basket_edit, name='edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
import mainapp.views as mainapp
import authapp.views as authapp
if settings.DEBUG:
    import debug_toolbar


urlpatterns = [
    url(r'^$', mainapp.main, name='main'),
    url(r'^auth/', include('authapp.urls', namespace='auth')),
    url(r'^products/', include('mainapp.urls', namespace='products')),
    url(r'^contacts/', mainapp.contacts, name='contacts'),
    url(r'^basket/', include('basketapp.urls', namespace='basket')),
    url(r'^admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    url(r'^admin/', admin.site.urls),
    url(r'^__debug__/', include(debug_toolbar.urls)),
    url(r'^social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.conf.urls import url

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   url('^$', mainapp.products, name='index'),
   url(r'^(?P<pk>\d+)/$', mainapp.product, name='product'),
   url(r'^category/(?P<pk>\d+)/$', mainapp.products, name='category'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='имя категория', max_length=128, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)

    def __str__(self):
        return '{} ({})'.format(self.name, self.category)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductCategory

def get_hot_product():
    return Product.objects.all().first()


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]

    return same_products


def main(request):
    product_list = Product.objects.all()

    return render(request, 'mainapp/index.html', context={'user': request.user , 'products': product_list})


def products(request, pk=None):
    links_menu = ProductCategory.objects.all()
    # basket = request.user.basket.all()[0] if request.user.is_authenticated else []

    if pk:
        if pk == '0':
            category = {'name': 'Все'}
            product_list = Product.objects.all()
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            product_list = Product.objects.filter(category=category.id)

        context = {
            'title': 'Продукты',
            'links_menu': links_menu,
            'products': product_list,
            'category': category,
        }
        return render(request, 'mainapp/product_list.html', context)
    else:
        product_list = Product.objects.all()

        hot_product = get_hot_product()
        same_products = get_same_products(hot_product)

        context = {
            'title': 'Продукты',
            'links_menu': links_menu,
            'hot_product': hot_product,
            'same_products': same_products,
        }
        return render(request, 'mainapp/products.html', context)


def product(request, pk):
    title = 'Продукт'

    context = {
        'title': title,
        'links_menu': ProductCategory.objects.all(),
        'product': get_object_or_404(Product, pk=pk),
    }

    return render(request, 'mainapp/product.html', context)


def contacts(request):
    return render(request, 'mainapp/contacts.html')

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static  %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
     <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {% block css %}
    
    {% endblock %}
</head>
<body>

{% block content %}
{% endblock %}
{% block js %}
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/basket_scripts.js' %}"></script>

{% endblock %}
</body>
</html>

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% block title %}
<title>Контакты</title>
{% endblock %}
{% block content %}
    {% include 'mainapp/includes/inc_menu.html' %}
<h1>Контакты</h1>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% block title %}
    <title>Главная</title>
{% endblock %}
{% block content %}
{% include 'mainapp/includes/inc_menu.html' %}

{% if user.is_authenticated %}
    <div>{{user.username|title}}</div>
    <a href="{% url 'auth:logout' %}">Выход</a>
{% else %}
    <a href="{% url 'auth:login' %}">Войдите</a> или <a href="{% url 'auth:register' %}">зарегестрируйте</a>
{% endif %}
    <ul>
        {%for product in products%}
            <li>{{product.name}} ({{ product.category }})</li>
        {%endfor%}
    </ul>
    <h1 class="test-class">Главная</h1>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
<div class="details">
    <div class="links clearfix">
        {% include 'mainapp/includes/inc_menu.html' %}
        {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ product.image }}"
                     alt="{{ product.short_desc }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#">
                        <img src="/media/{{ product.image }}" alt="вариант 1">
                    </a>
                </div>
                <div class="block">
                    <a href="#">
                        <img src="/media/{{ product.image }}" alt="вариант 2">
                    </a>
                </div>
                <div class="block">
                    <a href="#">
                        <img src="/media/{{ product.image }}" alt="вариант 3">
                    </a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ product.name }}</h3>
            <br>
            <p class="price"> {{ product.price }} <span>руб</span></p>
            <a href="{% url 'basket:add' product.pk %}" class="red-button">
                заказать
                <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ product.description }}
            </div>
        </div>
    </div>

</div>

<div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% block title %}
    <title>Продукты</title>
{% endblock %}

{% block content %}
    {% include 'mainapp/includes/inc_menu.html' %}

    {% include 'mainapp/includes/inc_categories_menu.html' %}
    <h1>Продукты</h1>
    {% for product in same_products %}
        <div>{{ product.name }}({{ product.category.name }})</div>
        {% if  product.image %}
            <img src="{{ product.image.url }}" alt="">

        {% endif %}
    {% endfor %}
    <div class="details-products">
        <div class="details-slider">
            <div class="slider-product">
                <img src="/media/{{ hot_product.image }}">
            </div>
            <div class="slider-control">
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                </div>
                <div class="block">
                    <a href="#"><img src="/media/{{ hot_product.image }}" alt=""></a>
                </div>
            </div>
        </div>

        <div class="description">
            <h3 class="big-bold">{{ hot_product.name }}</h3>
            <h3 class="red">горячее предложение</h3>
            <p class="price">{{ hot_product.price }} <span>руб</span></p>
            <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            <div class="description-text">
                {{ hot_product.description }}
            </div>
        </div>
    </div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    <div class="hero-white">
        <div class="header clearfix">
            {% include 'mainapp/includes/inc_menu.html' %}
        </div>
    </div>
{% endblock %}

{% block content %}
   <div class="category-products clearfix">
  {% for product in products %}
    <div class="block">
      <a href="{% url 'basket:add' product.pk %}">
        <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
        <div class="text">
          <img src="{% static 'img/icon-hover.png' %}" alt="hover">
          <h4>{{ product.name }}</h4>
          <p>{{ product.description }} </p>
        </div>
      </a>
    </div>
  {% endfor %}
</div>


    <div class="clr"></div>

{% endblock %}